package View;

import Logic.Channels.Channel;
import java.awt.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.time.LocalTime;

public class ScheduleJP extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    private Channel channelManager;

    public ScheduleJP(Channel channelManager) {
        this.channelManager = channelManager;
        initComponents();
        setupTableModel();
        updateSchedule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 51, 51));

        tblSchedule.setBackground(new java.awt.Color(0, 0, 0));
        tblSchedule.setForeground(new java.awt.Color(255, 255, 255));
        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Channel", "Program", "Schedule"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSchedule.setMinimumSize(new java.awt.Dimension(778, 523));
        tblSchedule.getTableHeader().setReorderingAllowed(false);
        tblSchedule.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblScheduleMouseMoved(evt);
            }
        });
        tblSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblScheduleMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tblSchedule);
        if (tblSchedule.getColumnModel().getColumnCount() > 0) {
            tblSchedule.getColumnModel().getColumn(0).setResizable(false);
            tblSchedule.getColumnModel().getColumn(1).setResizable(false);
            tblSchedule.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblScheduleMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblScheduleMouseMoved
        tblSchedule.setBackground(new Color(14, 144, 144));
    }//GEN-LAST:event_tblScheduleMouseMoved

    private void tblScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblScheduleMouseExited
        tblSchedule.setBackground(Color.BLACK);

    }//GEN-LAST:event_tblScheduleMouseExited


    private void setupTableModel() {
        String[] columnNames = {"Channel", "Program", "Schedule"};
        tableModel = new DefaultTableModel(null, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblSchedule.setModel(tableModel);

        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel);
        tblSchedule.setRowSorter(sorter);
        sorter.setComparator(2, (time1, time2) -> {
            LocalTime t1 = LocalTime.parse((String) time1);
            LocalTime t2 = LocalTime.parse((String) time2);
            return t1.compareTo(t2);
        });
    }

    public void updateSchedule() {
        tableModel.setRowCount(0);

        for (int i = 1; i <= 6; i++) {
            String channelName = "Channel " + i;
            String programs = channelManager.showChannel(i);

            if (!programs.isEmpty()) {
                String[] programsArray = programs.split(", ");
                for (String program : programsArray) {
                    String[] programDetails = program.split(": Schedule: ");
                    if (programDetails.length >= 2) {
                        String programInfo = programDetails[0].trim();
                        String[] programInfoDetails = programInfo.split(": ");
                        if (programInfoDetails.length >= 2) {
                            String programTitle = programInfoDetails[1].trim();
                            String timeRange = programDetails[1].trim();
                            String startTime = timeRange.split(" - ")[0].trim();
                            tableModel.addRow(new Object[]{channelName, programTitle, startTime});
                        } else {
                            System.err.println("Error: Formato de programa inválido: " + program);
                        }
                    } else {
                        System.err.println("Error: Formato de programa inválido: " + program);
                    }
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSchedule;
    // End of variables declaration//GEN-END:variables
}
