/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Logic.Channels.Channel;

/**
 *
 * @author ADMIN
 */
public class ViewChannelJP extends javax.swing.JPanel {

    int currentChannel;
    private Channel c;

    public ViewChannelJP() {
        c = new Channel();
        currentChannel = 1;
        c.creatChannels();
        initComponents();
        jtContent.setText(c.changeChannel(currentChannel) + "");
        jtCont.setText("Channel " + currentChannel);
        disableButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        txtChannelNumber = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        historyJP = new javax.swing.JPanel();
        jtContent = new javax.swing.JLabel();
        jtCont = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(778, 523));

        btnLeft.setBackground(new java.awt.Color(0, 0, 0));
        btnLeft.setForeground(new java.awt.Color(255, 255, 255));
        btnLeft.setText("<");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnRight.setBackground(new java.awt.Color(0, 0, 0));
        btnRight.setForeground(new java.awt.Color(255, 255, 255));
        btnRight.setText(">");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        txtChannelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChannelNumberActionPerformed(evt);
            }
        });

        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Channel number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("History");

        historyJP.setBackground(new java.awt.Color(0, 0, 0));
        historyJP.setLayout(new java.awt.GridLayout(1, 7, 2, 0));

        jtContent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtContent.setForeground(new java.awt.Color(255, 255, 255));
        jtContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jtCont.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtCont.setForeground(new java.awt.Color(255, 255, 255));
        jtCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(btnLeft)
                            .addGap(18, 18, 18)
                            .addComponent(jtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRight)
                            .addGap(39, 39, 39)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtChannelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jLabel3)
                            .addGap(648, 648, 648)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(historyJP, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jtCont, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jtCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtChannelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnGo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(historyJP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        disableButton();
        currentChannel--;
        jtContent.setText(c.changeChannel(currentChannel) + "");
        jtCont.setText("Channel " + currentChannel);

        if (currentChannel == 1) {
            btnLeft.setEnabled(false);
        }
        btnRight.setEnabled(true);
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        currentChannel++;
        jtContent.setText(c.changeChannel(currentChannel) + "");
        jtCont.setText("Channel " + currentChannel);

        if (currentChannel == 6) {
            btnRight.setEnabled(false);
        }
        btnLeft.setEnabled(true);
    }//GEN-LAST:event_btnRightActionPerformed

    private void txtChannelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChannelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChannelNumberActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        int destinyChannel = Integer.parseInt(txtChannelNumber.getText());
        jtContent.setText(c.channelNavigation(currentChannel, destinyChannel));
        currentChannel = destinyChannel;
        jtCont.setText("Channel " + currentChannel);
        if (currentChannel == 6) {
            btnRight.setEnabled(false);
            btnLeft.setEnabled(true);
        }
        if (currentChannel == 1) {
            btnLeft.setEnabled(false);
            btnRight.setEnabled(true);
        }
    }//GEN-LAST:event_btnGoActionPerformed

    public void disableButton() {
        if (currentChannel == 1) {
            btnLeft.setEnabled(false);
        }
        if (currentChannel == 5) {
            btnRight.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JPanel historyJP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jtCont;
    private javax.swing.JLabel jtContent;
    private javax.swing.JTextField txtChannelNumber;
    // End of variables declaration//GEN-END:variables
}
